import type { LightingQuery } from './pbrpIntentAnalyzer.js';
import type { KnowledgeSelection } from './pbrpKnowledgeSelector.js';

/**
 * PHASE-PROJECT-BRAIN-INTEGRATION-005: PBRP Runtime Execution Preparation V1.
 *
 * Knowledge Composer (04_PBRP_Execution_Architecture_Revision_V2.txt,
 * "Revision 04"; 04A_PBRP_Engineering_Recommendations.txt,
 * "Recommendation 03: Deterministic Knowledge Composer ... Non Goal: LLM
 * Reasoning"). Merges the Knowledge Selector's output into one Scene
 * Context using fixed rules -- no LLM call, no external API. Conflict
 * resolution is a small, explicit priority table, not free-form reasoning.
 */

export type LightingDescriptor = {
  time_of_day: LightingQuery['time_of_day'];
  weather: LightingQuery['weather'];
  descriptor: string;
};

export type ConsistencyRule = {
  world_identity_lock: 'PASS';
  generic_harbor_regression: false;
  rule_text: string;
};

export type SceneContext = {
  character_dna_applied: boolean;
  character_summary: string | null;
  style_dna_applied: boolean;
  style_summary: string | null;
  shot_grammar_applied: boolean;
  shot_summary: string | null;
  lighting: LightingDescriptor;
  consistency: ConsistencyRule;
  negative_rules: string[];
  unresolved_capabilities: string[];
  compose_mode: 'deterministic_rule_engine_v1';
};

// Fixed rule table (Recommendation 03: "Priority Rule"). Lighting descriptor
// text is looked up, never generated by an LLM.
const LIGHTING_DESCRIPTOR_RULES: Record<string, string> = {
  'night|rain': 'rain-slicked deck under low, cold artificial light; heavy overcast night sky',
  'night|clear': 'clear cold night sky, moonlit highlights, deep shadow falloff',
  'night|unspecified': 'low ambient night lighting, soft rim light',
  'golden_hour|unspecified': 'warm golden-hour side light, long soft shadows',
  'golden_hour|clear': 'warm golden-hour side light, long soft shadows, clear sky',
  'day|unspecified': 'bright even daylight, natural fill',
  'day|clear': 'bright clear daylight, hard sun highlights',
  'unspecified|rain': 'overcast rain-diffused light, no strong shadows',
  'unspecified|unspecified': 'neutral, balanced natural light',
};

// Lookup order: exact (time_of_day|weather) match first; if the exact
// combination has no fixed rule, fall back to the same time_of_day with
// unspecified weather (never silently collapse straight to the fully
// generic default while still labeling the result with a specific
// time_of_day/weather -- that produced a real inconsistency during this
// phase's own verification: a golden_hour+rain query fell through to the
// "neutral, balanced natural light" default while still being labeled
// time_of_day=golden_hour/weather=rain, which contradicted its own label).
function resolveLightingDescriptor(query: LightingQuery): LightingDescriptor {
  const exactKey = `${query.time_of_day}|${query.weather}`;
  const timeOnlyKey = `${query.time_of_day}|unspecified`;
  const descriptor =
    LIGHTING_DESCRIPTOR_RULES[exactKey] ??
    LIGHTING_DESCRIPTOR_RULES[timeOnlyKey] ??
    LIGHTING_DESCRIPTOR_RULES['unspecified|unspecified'];
  return { time_of_day: query.time_of_day, weather: query.weather, descriptor };
}

// Fixed consistency rule, matching the same world-identity-lock convention
// used throughout the repository's real movie-reconstruction pipeline
// (`world_identity_lock: PASS`, `generic_harbor_regression: false`).
function buildConsistencyRule(): ConsistencyRule {
  return {
    world_identity_lock: 'PASS',
    generic_harbor_regression: false,
    rule_text: 'Maintain Gonegi world identity; do not drift into a generic, unbranded harbor/period backdrop.',
  };
}

function buildNegativeRules(selection: KnowledgeSelection): string[] {
  const rules = [
    'no generic harbor drift',
    'no anachronistic modern elements',
    'no duplicate or malformed limbs/faces',
  ];
  if (!selection.character) {
    rules.push('no invented character identity outside the selected Character DNA');
  }
  return rules;
}

// =========================================================================
// PHASE-PBRP-AI-STUDIO-NATIVE-SCENARIO-ADAPTER-004: source-aware validation
// (items 6-7). `buildConsistencyRule()`/`buildNegativeRules()` above remain
// a single, fixed, source-agnostic template -- this audit does not change
// that text (not asked for; verification, not rewrite), it checks whether
// the fixed wording is contradicted by each source's own real data. Kept
// as a pure function (no new file I/O in this module, consistent with the
// Composer's existing design) -- callers that also want to cross-check the
// wording against `datasets/movie_reconstruction/world-translation-rules.json`'s
// real `forbidden_outcomes` list (which does list "Generic Harbor Scene" as
// of this phase's own read-only analysis) do that read themselves.
// =========================================================================

export type SourceAwareRuleAudit = {
  anchor_id: string | null;
  anchor_generic_harbor_regression_field: boolean | null;
  field_matches_expectation: boolean;
  hardcoded_wording_mentions_harbor: boolean;
  audit_note: string;
};

/**
 * Checks the fixed `rule_text`/`generic_harbor_regression` output against
 * the *real* per-anchor `generic_harbor_regression` field (recovered in
 * `pbrpKnowledgeRepository.ts`) for the source that actually produced this
 * scene. Confirmed real and disclosed: this field is present (and always
 * `false`) on every Spirited Away anchor checked so far, and absent
 * (`null`) on every Titanic anchor checked so far -- both are treated as
 * "matches expectation" (a `null` field cannot contradict anything; a real
 * `false` is consistent with the fixed rule's implied guarantee). Only a
 * real `true` would indicate the fixed wording contradicts the source's
 * own data -- not observed in either source during this phase's analysis.
 */
export function auditConsistencyRuleAgainstSource(
  selection: KnowledgeSelection,
  consistency: ConsistencyRule
): SourceAwareRuleAudit {
  const anchor = selection.character;
  const fieldValue = anchor ? anchor.generic_harbor_regression : null;
  const field_matches_expectation = fieldValue === null || fieldValue === false;

  return {
    anchor_id: anchor?.anchor_id ?? null,
    anchor_generic_harbor_regression_field: fieldValue,
    field_matches_expectation,
    hardcoded_wording_mentions_harbor: consistency.rule_text.toLowerCase().includes('harbor'),
    audit_note: fieldValue === null
      ? "source has no generic_harbor_regression field at all (confirmed real for every Titanic anchor checked) -- the fixed rule_text's 'harbor' wording cannot be contradicted by a field that doesn't exist in this source"
      : `source's own generic_harbor_regression=${fieldValue} -- ${field_matches_expectation ? 'consistent with' : 'CONTRADICTS'} the fixed rule_text's implied guarantee`,
  };
}

export function composeKnowledge(
  selection: KnowledgeSelection,
  lightingQuery: LightingQuery
): SceneContext {
  return {
    character_dna_applied: selection.character !== null,
    character_summary: selection.character
      ? `${selection.character.anchor_id}: ${selection.character.semantic_meaning}`
      : null,
    style_dna_applied: selection.style !== null,
    style_summary: selection.style
      ? `${selection.style.composition_id} (priority_score=${selection.style.priority_score}), ${selection.style.descriptor}`
      : null,
    shot_grammar_applied: selection.shot !== null,
    shot_summary: selection.shot
      ? `${selection.shot.shot_id}: ${selection.shot.shot_type}`
      : null,
    lighting: resolveLightingDescriptor(lightingQuery),
    consistency: buildConsistencyRule(),
    negative_rules: buildNegativeRules(selection),
    unresolved_capabilities: selection.unresolved_capabilities,
    compose_mode: 'deterministic_rule_engine_v1',
  };
}
