import type { TestKikiFrameGrammarProfile } from './testKikiExtractionSchema.js';

export const TEST_KIKI_FRAME_GRAMMAR_PROFILES: readonly TestKikiFrameGrammarProfile[] =
  Object.freeze([
    Object.freeze({
      camera: Object.freeze({
        camera_distance: 'wide',
        camera_height: 'eye-level',
        camera_angle: 'three-quarter',
        lens_feeling: 'wide-expansive',
        framing_type: 'establishing-wide',
        subject_position: 'right-third',
      }),
      acting: Object.freeze({
        gaze_direction: 'toward-horizon',
        head_direction: 'level',
        hand_activity: 'at-side',
        posture: 'upright-neutral',
        body_weight_distribution: 'even',
      }),
      daily_life: Object.freeze({
        activity: 'observing',
        object_interaction: 'none',
        environmental_touchpoint: 'ground-stand',
      }),
      location: Object.freeze({
        space_type: 'exterior-harbor',
        architectural_feature: 'roofline-cluster',
        depth_cue: 'deep-horizon',
        navigation_pattern: 'open-plaza',
      }),
      emotion: Object.freeze({ emotion_state: 'curious' }),
      story: Object.freeze({ scene_function: 'establish' }),
    }),
    Object.freeze({
      camera: Object.freeze({
        camera_distance: 'mid',
        camera_height: 'waist-level',
        camera_angle: 'profile',
        lens_feeling: 'normal-neutral',
        framing_type: 'rule-of-thirds',
        subject_position: 'left-third',
      }),
      acting: Object.freeze({
        gaze_direction: 'off-camera-right',
        head_direction: 'turn-away',
        hand_activity: 'holding-object',
        posture: 'walking-stride',
        body_weight_distribution: 'forward-weighted',
      }),
      daily_life: Object.freeze({
        activity: 'traveling',
        object_interaction: 'handheld-prop',
        environmental_touchpoint: 'ground-walk',
      }),
      location: Object.freeze({
        space_type: 'exterior-street',
        architectural_feature: 'shopfront-row',
        depth_cue: 'shallow-layered',
        navigation_pattern: 'linear-path',
      }),
      emotion: Object.freeze({ emotion_state: 'focused' }),
      story: Object.freeze({ scene_function: 'bridge' }),
    }),
    Object.freeze({
      camera: Object.freeze({
        camera_distance: 'extreme-wide',
        camera_height: 'high',
        camera_angle: 'rear',
        lens_feeling: 'deep-focus',
        framing_type: 'environmental-depth',
        subject_position: 'midground-dominant',
      }),
      acting: Object.freeze({
        gaze_direction: 'upward-scan',
        head_direction: 'chin-up',
        hand_activity: 'braced',
        posture: 'forward-lean',
        body_weight_distribution: 'in-motion-shift',
      }),
      daily_life: Object.freeze({
        activity: 'transiting',
        object_interaction: 'vehicle-control',
        environmental_touchpoint: 'airborne',
      }),
      location: Object.freeze({
        space_type: 'exterior-sky',
        architectural_feature: 'none-dominant',
        depth_cue: 'aerial-depth',
        navigation_pattern: 'aerial-route',
      }),
      emotion: Object.freeze({ emotion_state: 'alert' }),
      story: Object.freeze({ scene_function: 'bridge' }),
    }),
    Object.freeze({
      camera: Object.freeze({
        camera_distance: 'mid-close',
        camera_height: 'eye-level',
        camera_angle: 'over-shoulder',
        lens_feeling: 'shallow-focus',
        framing_type: 'layered-foreground',
        subject_position: 'foreground-dominant',
      }),
      acting: Object.freeze({
        gaze_direction: 'toward-object',
        head_direction: 'tilt-down',
        hand_activity: 'resting-on-surface',
        posture: 'seated',
        body_weight_distribution: 'rear-weighted',
      }),
      daily_life: Object.freeze({
        activity: 'resting',
        object_interaction: 'container-carry',
        environmental_touchpoint: 'surface-lean',
      }),
      location: Object.freeze({
        space_type: 'interior-room',
        architectural_feature: 'window-grid',
        depth_cue: 'shallow-layered',
        navigation_pattern: 'static-observe',
      }),
      emotion: Object.freeze({ emotion_state: 'neutral' }),
      story: Object.freeze({ scene_function: 'bridge' }),
    }),
    Object.freeze({
      camera: Object.freeze({
        camera_distance: 'mid',
        camera_height: 'ground-level',
        camera_angle: 'three-quarter',
        lens_feeling: 'normal-neutral',
        framing_type: 'centered-subject',
        subject_position: 'center',
      }),
      acting: Object.freeze({
        gaze_direction: 'downward-task',
        head_direction: 'chin-down',
        hand_activity: 'gesture-low',
        posture: 'crouched',
        body_weight_distribution: 'single-leg-lean',
      }),
      daily_life: Object.freeze({
        activity: 'working',
        object_interaction: 'tool-use',
        environmental_touchpoint: 'ground-walk',
      }),
      location: Object.freeze({
        space_type: 'exterior-street',
        architectural_feature: 'stair-ramp',
        depth_cue: 'deep-alley',
        navigation_pattern: 'vertical-ascent',
      }),
      emotion: Object.freeze({ emotion_state: 'focused' }),
      story: Object.freeze({ scene_function: 'bridge' }),
    }),
    Object.freeze({
      camera: Object.freeze({
        camera_distance: 'wide',
        camera_height: 'high',
        camera_angle: 'top-down',
        lens_feeling: 'tele-compressed',
        framing_type: 'establishing-wide',
        subject_position: 'background-dominant',
      }),
      acting: Object.freeze({
        gaze_direction: 'off-camera-left',
        head_direction: 'level',
        hand_activity: 'at-side',
        posture: 'walking-stride',
        body_weight_distribution: 'forward-weighted',
      }),
      daily_life: Object.freeze({
        activity: 'traveling',
        object_interaction: 'none',
        environmental_touchpoint: 'ground-walk',
      }),
      location: Object.freeze({
        space_type: 'exterior-harbor',
        architectural_feature: 'bridge-structure',
        depth_cue: 'deep-horizon',
        navigation_pattern: 'corridor-flow',
      }),
      emotion: Object.freeze({ emotion_state: 'neutral' }),
      story: Object.freeze({ scene_function: 'bridge' }),
    }),
    Object.freeze({
      camera: Object.freeze({
        camera_distance: 'close',
        camera_height: 'waist-level',
        camera_angle: 'profile',
        lens_feeling: 'shallow-focus',
        framing_type: 'rule-of-thirds',
        subject_position: 'left-third',
      }),
      acting: Object.freeze({
        gaze_direction: 'over-shoulder-target',
        head_direction: 'turn-away',
        hand_activity: 'gesture-mid',
        posture: 'upright-neutral',
        body_weight_distribution: 'even',
      }),
      daily_life: Object.freeze({
        activity: 'interacting',
        object_interaction: 'handheld-prop',
        environmental_touchpoint: 'doorway-threshold',
      }),
      location: Object.freeze({
        space_type: 'mixed-threshold',
        architectural_feature: 'shopfront-row',
        depth_cue: 'shallow-layered',
        navigation_pattern: 'linear-path',
      }),
      emotion: Object.freeze({ emotion_state: 'curious' }),
      story: Object.freeze({ scene_function: 'bridge' }),
    }),
    Object.freeze({
      camera: Object.freeze({
        camera_distance: 'mid-close',
        camera_height: 'eye-level',
        camera_angle: 'three-quarter',
        lens_feeling: 'normal-neutral',
        framing_type: 'environmental-depth',
        subject_position: 'right-third',
      }),
      acting: Object.freeze({
        gaze_direction: 'toward-horizon',
        head_direction: 'level',
        hand_activity: 'in-motion',
        posture: 'running-stride',
        body_weight_distribution: 'in-motion-shift',
      }),
      daily_life: Object.freeze({
        activity: 'traveling',
        object_interaction: 'vehicle-control',
        environmental_touchpoint: 'airborne',
      }),
      location: Object.freeze({
        space_type: 'exterior-sky',
        architectural_feature: 'none-dominant',
        depth_cue: 'aerial-depth',
        navigation_pattern: 'aerial-route',
      }),
      emotion: Object.freeze({ emotion_state: 'alert' }),
      story: Object.freeze({ scene_function: 'bridge' }),
    }),
    Object.freeze({
      camera: Object.freeze({
        camera_distance: 'wide',
        camera_height: 'eye-level',
        camera_angle: 'front',
        lens_feeling: 'wide-expansive',
        framing_type: 'silhouette-frame',
        subject_position: 'center',
      }),
      acting: Object.freeze({
        gaze_direction: 'off-camera-right',
        head_direction: 'chin-up',
        hand_activity: 'at-side',
        posture: 'upright-neutral',
        body_weight_distribution: 'even',
      }),
      daily_life: Object.freeze({
        activity: 'observing',
        object_interaction: 'none',
        environmental_touchpoint: 'ground-stand',
      }),
      location: Object.freeze({
        space_type: 'exterior-harbor',
        architectural_feature: 'tower-spire',
        depth_cue: 'deep-horizon',
        navigation_pattern: 'static-observe',
      }),
      emotion: Object.freeze({ emotion_state: 'relieved' }),
      story: Object.freeze({ scene_function: 'resolve' }),
    }),
    Object.freeze({
      camera: Object.freeze({
        camera_distance: 'mid',
        camera_height: 'waist-level',
        camera_angle: 'rear',
        lens_feeling: 'deep-focus',
        framing_type: 'establishing-wide',
        subject_position: 'background-dominant',
      }),
      acting: Object.freeze({
        gaze_direction: 'toward-horizon',
        head_direction: 'level',
        hand_activity: 'at-side',
        posture: 'walking-stride',
        body_weight_distribution: 'forward-weighted',
      }),
      daily_life: Object.freeze({
        activity: 'transiting',
        object_interaction: 'none',
        environmental_touchpoint: 'ground-walk',
      }),
      location: Object.freeze({
        space_type: 'exterior-street',
        architectural_feature: 'roofline-cluster',
        depth_cue: 'deep-alley',
        navigation_pattern: 'linear-path',
      }),
      emotion: Object.freeze({ emotion_state: 'neutral' }),
      story: Object.freeze({ scene_function: 'resolve' }),
    }),
  ]);
