import {
  REAL_VIDEO_INTAKE_DATASET_INTENT,
  REAL_VIDEO_INTAKE_DURATION_SECONDS,
  REAL_VIDEO_INTAKE_SAFETY_NOTE,
  REAL_VIDEO_INTAKE_SOURCE_FILENAME,
  REAL_VIDEO_INTAKE_SOURCE_PATH,
  REAL_VIDEO_INTAKE_SOURCE_ROLE,
  buildRealVideoIntakeManifest,
  computeRealVideoIntakeManifestFingerprint,
} from "./real-video-intake-manifest.ts";

export const REAL_VIDEO_INTAKE_MANIFEST_OUTPUT_EXAMPLE = buildRealVideoIntakeManifest();

export const REAL_VIDEO_INTAKE_MANIFEST_FINGERPRINT = computeRealVideoIntakeManifestFingerprint(
  REAL_VIDEO_INTAKE_MANIFEST_OUTPUT_EXAMPLE
);

export const REAL_VIDEO_INTAKE_MANIFEST_ROOT_OUTPUT_EXAMPLE = Object.freeze({
  sourceFilename: REAL_VIDEO_INTAKE_SOURCE_FILENAME,
  sourcePath: REAL_VIDEO_INTAKE_SOURCE_PATH,
  durationSeconds: REAL_VIDEO_INTAKE_DURATION_SECONDS,
  sourceRole: REAL_VIDEO_INTAKE_SOURCE_ROLE,
  datasetIntent: REAL_VIDEO_INTAKE_DATASET_INTENT,
  safetyNote: REAL_VIDEO_INTAKE_SAFETY_NOTE,
});
