import { IMAGE_GENERATION_REQUEST_OUTPUT_EXAMPLE } from "./image-generation-request.fixtures.ts";
import { AI_STUDIO_TEST_EXPORT_OUTPUT_EXAMPLE } from "./ai-studio-test-export.fixtures.ts";
import { IMAGE_RESULT_EVALUATION_OUTPUT_EXAMPLE } from "./image-result-evaluation.fixtures.ts";
import { PROMPT_POLICY_FEEDBACK_OUTPUT_EXAMPLE } from "./prompt-policy-feedback.fixtures.ts";
import { NEXT_GENERATION_REQUEST_OUTPUT_EXAMPLE } from "./next-generation-request-composer.fixtures.ts";
import {
  MULTI_ITERATION_FEEDBACK_MEMORY_OUTPUT_EXAMPLE,
  NEXT_GENERATION_REQUEST_REGRESSION_EXAMPLE,
} from "./multi-iteration-feedback-memory.fixtures.ts";
import { buildMultiIterationFeedbackMemory } from "./multi-iteration-feedback-memory.ts";
import { MULTI_ITERATION_FEEDBACK_MEMORY_INPUT_EXAMPLE } from "./multi-iteration-feedback-memory.fixtures.ts";
import { buildGenerationSessionExport } from "./generation-session-export.ts";

export const GENERATION_SESSION_EXPORT_REQUEST_EXAMPLE = IMAGE_GENERATION_REQUEST_OUTPUT_EXAMPLE;

export const GENERATION_SESSION_EXPORT_AI_STUDIO_EXAMPLE = AI_STUDIO_TEST_EXPORT_OUTPUT_EXAMPLE;

export const GENERATION_SESSION_EXPORT_EVALUATION_EXAMPLE = IMAGE_RESULT_EVALUATION_OUTPUT_EXAMPLE;

export const GENERATION_SESSION_EXPORT_FEEDBACK_EXAMPLE = PROMPT_POLICY_FEEDBACK_OUTPUT_EXAMPLE;

export const GENERATION_SESSION_EXPORT_NEXT_REQUEST_EXAMPLE = NEXT_GENERATION_REQUEST_OUTPUT_EXAMPLE;

export const GENERATION_SESSION_EXPORT_MEMORY_EXAMPLE = MULTI_ITERATION_FEEDBACK_MEMORY_OUTPUT_EXAMPLE;

export const GENERATION_SESSION_EXPORT_INPUT_EXAMPLE = Object.freeze({
  request: GENERATION_SESSION_EXPORT_REQUEST_EXAMPLE,
  aiStudioExport: GENERATION_SESSION_EXPORT_AI_STUDIO_EXAMPLE,
  evaluation: GENERATION_SESSION_EXPORT_EVALUATION_EXAMPLE,
  feedback: GENERATION_SESSION_EXPORT_FEEDBACK_EXAMPLE,
  nextRequest: GENERATION_SESSION_EXPORT_NEXT_REQUEST_EXAMPLE,
  memory: GENERATION_SESSION_EXPORT_MEMORY_EXAMPLE,
  sessionIndex: 0,
});

export const GENERATION_SESSION_EXPORT_OUTPUT_EXAMPLE = buildGenerationSessionExport(
  GENERATION_SESSION_EXPORT_INPUT_EXAMPLE
);

export const GENERATION_SESSION_EXPORT_ID_EXPECTED = "generation-session-001";

export const GENERATION_SESSION_SOURCE_REQUEST_ID_EXPECTED = "image-request-001";

export const GENERATION_SESSION_NEXT_REQUEST_ID_EXPECTED = "image-request-002";

export const MULTI_ITERATION_FEEDBACK_MEMORY_REGRESSION_EXAMPLE = buildMultiIterationFeedbackMemory(
  MULTI_ITERATION_FEEDBACK_MEMORY_INPUT_EXAMPLE
);

export const NEXT_GENERATION_REQUEST_COMPOSER_REGRESSION_EXAMPLE = NEXT_GENERATION_REQUEST_REGRESSION_EXAMPLE;
